### ISSUE TITLE
Allow setting default flags in tsconfig-migrations flag in the datocms.config.json

### ISSUE THREAD

**Issue by moshie** [datocms/cli#10]
I am not sure if this exists already I couldn't find any documentation on it?

```
{
  "profiles": {
    "default": {
      "logLevel": "BODY",
      "migrations-tsconfig": "tsconfig.migrations.json",
      "migrations": {
        "directory": "./migrations",
        "modelApiKey": "schema_migration"
      }
    }
  }
}
```

**Comment by stefanoverna** [comment]
I'm not sure what you're asking @moshie :/

**Comment by stefanoverna** [comment]
We recently added a "migrations.tsconfig" configuration: https://github.com/datocms/cli/commit/97da23407c36da2edd2507affdc7fc48cd5444be is that what you're asking for?
