### ISSUE TITLE
Migration autogeneration fails if the source environment is empty

### ISSUE THREAD

**Issue by illarionvk** [datocms/cli#15]
The autogenerate command fails with a `TypeError: Cannot read properties of undefined (reading 'filter')` error if the source (primary) environment has no models or blocks.

The command completed successfully as soon as I created a model in the primary environment.

Example command:

```sh
# `next` is the name of the sandbox environment
datocms migrations:new 'add company' --ts --autogenerate='next'
```

<img width="570" alt="Screenshot 2023-06-26 at 16 51 24" src="https://github.com/datocms/cli/assets/5012724/0541f244-c9a2-42a1-af20-4df4b07afbff">

**Comment by stefanoverna** [comment]
Sorry for the inconvenience, please try with v1.1.9!
